payloads/edk2: keep UniversalPayload compatibility
Change-Id: Icb5429faa7265f4ab2fb3b9ebc9f7550d9ff2c0a
Signed-off-by: Sean Rhodes <sean@starlabs.systems>

diff --git a/payloads/external/edk2/Makefile b/payloads/external/edk2/Makefile
--- a/payloads/external/edk2/Makefile
+++ b/payloads/external/edk2/Makefile
@@ -60,6 +60,7 @@ export PACKAGES_PATH := $(EDK2_PATH)
 endif
 
 EDK2_UEFIPAYLOAD_OUT ?= ../../../build/UEFIPAYLOAD.fd
+EDK2_UNIVERSAL_PAYLOAD_OUT ?= ../../../build/UniversalPayload.fit
 EDK2_CDK2_OUT ?= ../../../build/cdk2-coreboot-image.elf
 HOSTCC ?= cc
 ifndef CDK2_NATIVE_CC
@@ -88,14 +89,14 @@ CDK2_COREBOOT_CONFIG_KEYS := \
 	CONFIG_CDK2_LAPIC_TIMER \
 	CONFIG_CDK2_HPET_TIMER
 
-ifneq ($(CONFIG_EDK2_CDK2),y)
+ifeq ($(CONFIG_EDK2_UEFIPAYLOAD),y)
 	BUILD_STR += -p UefiPayloadPkg/UefiPayloadPkg.dsc
 endif
 BUILD_STR += -t GCC
 BUILD_STR += -D BOOTLOADER=COREBOOT
 ifneq ($(V),1)
 BUILD_STR += -q
-ifneq ($(CONFIG_EDK2_CDK2),y)
+ifeq ($(CONFIG_EDK2_UEFIPAYLOAD),y)
 BUILD_STR += -s
 endif
 endif
@@ -539,6 +540,26 @@ UefiPayloadPkg: $(WORKSPACE)/Build/UefiPayloadPkgX64/$(RELEASE_STR)_GCC/FV/UEFIP
 	mv $(WORKSPACE)/Build/UefiPayloadPkgX64/$(RELEASE_STR)_GCC/FV/UEFIPAYLOAD.fd \
 		$(EDK2_UEFIPAYLOAD_OUT)
 
+$(WORKSPACE)/Build/UefiPayloadPkgIA32/UniversalPayload.fit: \
+	prep print
+	cd $(WORKSPACE); \
+		source $(EDK2_PATH)/edksetup.sh; \
+		$(EDK2_ENSURE_FMP_CERT_INC) \
+		echo -n "EDK2: Building... "; \
+		bash $(EDK2_PATH)/UefiPayloadPkg/UniversalPayloadBuild.sh -a IA32 -b $(RELEASE_STR) $(BUILD_STR) \
+			-D BUILD_ARCH=IA32 --Fit \
+			--pcd gUefiPayloadPkgTokenSpaceGuid.PcdHandOffFdtEnable=TRUE
+		if [ ! -f $@ ]; then \
+			echo "Failed!"; \
+			exit 1; \
+		fi
+		echo "Success!"; \
+
+UniversalPayload: $(WORKSPACE)/Build/UefiPayloadPkgIA32/UniversalPayload.fit
+	mkdir -p $(dir $(EDK2_UNIVERSAL_PAYLOAD_OUT))
+	mv $(WORKSPACE)/Build/UefiPayloadPkgIA32/UniversalPayload.fit \
+		$(EDK2_UNIVERSAL_PAYLOAD_OUT)
+
 cdk2: $(EDK2_PATH) checktools_cdk2 $(EDK2_CDK2_DEPS)
 	set -e; \
 	cdk2_build_dir=Build/cdk2-coreboot; \
@@ -633,7 +654,7 @@ endif
 distclean:
 	rm -rf $(WORKSPACE)
 
-.PHONY: $(EDK2_PATH) checktools checktools_cdk2 logo UefiPayloadPkg cdk2 clean distclean
+.PHONY: $(EDK2_PATH) checktools checktools_cdk2 logo UefiPayloadPkg UniversalPayload cdk2 clean distclean
 
 .PHONY: coreboot_capsule capsule_keys
 
